# Generated by Django 2.1.7 on 2019-03-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='final_product_photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
