# Generated by Django 2.1.7 on 2019-03-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20190313_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredieantmeasurement',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'gram'), ('mg', 'milligram'), ('l', 'liter'), ('ml', 'mililiter'), ('oz', 'ounce'), ('floz', 'fluid oz'), ('cup', 'cup'), ('lb', 'lb'), ('tsp', 'teaspoon'), ('tbs', 'tablespoon'), ('qrt', 'quart'), ('pt', 'pint')], default='g', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='IngredieantMeasurement',
        ),
    ]
