# Generated by Django 2.1.7 on 2019-03-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20190313_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit_type',
            field=models.CharField(choices=[('v', 'Volume'), ('w', 'Weight')], default='w', max_length=200),
            preserve_default=False,
        ),
    ]
