# Generated by Django 2.1.7 on 2019-03-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_ingredient_unit_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipestep',
            options={'ordering': ('order',)},
        ),
    ]
